Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure(figsize=(12,5))


axes = fig.add_subplot(1,2,1)
plt.plot(x_train,y_train,'bo',scaley=True, scalex=True)
plt.plot(x_test,y_test,'ro',scaley=True, scalex=True,alpha=0.3)

line, = axes.plot(sorted(x_train), predecir[0,:], 'r-')

# Animaci√≥n
ani = FuncAnimation(fig=fig, func=animate, interval=100)

# Visualizaci√≥n de Modelo para Datos Test
axes2 = fig.add_subplot(1,2,2)
predecir_test = model.predict(sorted(x_test),verbose=0).reshape(-1)
plt.plot(x_train,y_train,'bo',scaley=True, scalex=True,alpha=0.1)
plt.plot(x_test,y_test,'ro',scaley=True, scalex=True)
plt.plot(sorted(x_test),predecir_test,'r--',scaley=True, scalex=True)

# Etiquetas de los Ejes
plt.xlabel('$x$',fontsize=15)
plt.ylabel('$y$',rotation=0,fontsize=15)

# Leyendas
plt.legend(['Train','Test','Red Neuronal'])
plt.title('Modelo Resultante para Test');

# Video para renderizar
video = ani.to_html5_video()
html = display.HTML(video)
display.display(html)

plt.close()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mRuntimeError[0m                              Traceback (most recent call last)
Input [1;32mIn [7][0m, in [0;36m<cell line: 29>[1;34m()[0m
[0;32m     26[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mModelo Resultante para Test[39m[38;5;124m'[39m);
[0;32m     28[0m [38;5;66;03m# Video para renderizar[39;00m
[1;32m---> 29[0m video [38;5;241m=[39m [43mani[49m[38;5;241;43m.[39;49m[43mto_html5_video[49m[43m([49m[43m)[49m
[0;32m     30[0m html [38;5;241m=[39m display[38;5;241m.[39mHTML(video)
[0;32m     31[0m display[38;5;241m.[39mdisplay(html)

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\animation.py:1264[0m, in [0;36mAnimation.to_html5_video[1;34m(self, embed_limit)[0m
[0;32m   1261[0m path [38;5;241m=[39m Path(tmpdir, [38;5;124m"[39m[38;5;124mtemp.m4v[39m[38;5;124m"[39m)
[0;32m   1262[0m [38;5;66;03m# We create a writer manually so that we can get the[39;00m
[0;32m   1263[0m [38;5;66;03m# appropriate size for the tag[39;00m
[1;32m-> 1264[0m Writer [38;5;241m=[39m [43mwriters[49m[43m[[49m[43mmpl[49m[38;5;241;43m.[39;49m[43mrcParams[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43manimation.writer[39;49m[38;5;124;43m'[39;49m[43m][49m[43m][49m
[0;32m   1265[0m writer [38;5;241m=[39m Writer(codec[38;5;241m=[39m[38;5;124m'[39m[38;5;124mh264[39m[38;5;124m'[39m,
[0;32m   1266[0m                 bitrate[38;5;241m=[39mmpl[38;5;241m.[39mrcParams[[38;5;124m'[39m[38;5;124manimation.bitrate[39m[38;5;124m'[39m],
[0;32m   1267[0m                 fps[38;5;241m=[39m[38;5;241m1000.[39m [38;5;241m/[39m [38;5;28mself[39m[38;5;241m.[39m_interval)
[0;32m   1268[0m [38;5;28mself[39m[38;5;241m.[39msave([38;5;28mstr[39m(path), writer[38;5;241m=[39mwriter)

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\animation.py:151[0m, in [0;36mMovieWriterRegistry.__getitem__[1;34m(self, name)[0m
[0;32m    149[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mis_available(name):
[0;32m    150[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_registered[name]
[1;32m--> 151[0m [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mRequested MovieWriter ([39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m) not available[39m[38;5;124m"[39m)

[1;31mRuntimeError[0m: Requested MovieWriter (ffmpeg) not available
RuntimeError: Requested MovieWriter (ffmpeg) not available

