Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#from google.colab import ##drive correr solo en colab
#drive.mount('/content/gdrive')
counties = pd.read_excel("https://github.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/blob/main/Python/Datos/counties.xlsx?raw=true")#cambiar direcciÃ³n
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\compat\_optional.py:138[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    137[0m [38;5;28;01mtry[39;00m:
[1;32m--> 138[0m     module [38;5;241m=[39m [43mimportlib[49m[38;5;241;43m.[39;49m[43mimport_module[49m[43m([49m[43mname[49m[43m)[49m
[0;32m    139[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py:127[0m, in [0;36mimport_module[1;34m(name, package)[0m
[0;32m    126[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m--> 127[0m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[38;5;241;43m.[39;49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

File [1;32m<frozen importlib._bootstrap>:1030[0m, in [0;36m_gcd_import[1;34m(name, package, level)[0m

File [1;32m<frozen importlib._bootstrap>:1007[0m, in [0;36m_find_and_load[1;34m(name, import_)[0m

File [1;32m<frozen importlib._bootstrap>:984[0m, in [0;36m_find_and_load_unlocked[1;34m(name, import_)[0m

[1;31mModuleNotFoundError[0m: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

[1;31mImportError[0m                               Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m#from google.colab import ##drive correr solo en colab[39;00m
[0;32m      2[0m [38;5;66;03m#drive.mount('/content/gdrive')[39;00m
[1;32m----> 3[0m counties [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_excel[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mhttps://github.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/blob/main/Python/Datos/counties.xlsx?raw=true[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\util\_decorators.py:311[0m, in [0;36mdeprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper[1;34m(*args, **kwargs)[0m
[0;32m    305[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(args) [38;5;241m>[39m num_allow_args:
[0;32m    306[0m     warnings[38;5;241m.[39mwarn(
[0;32m    307[0m         msg[38;5;241m.[39mformat(arguments[38;5;241m=[39marguments),
[0;32m    308[0m         [38;5;167;01mFutureWarning[39;00m,
[0;32m    309[0m         stacklevel[38;5;241m=[39mstacklevel,
[0;32m    310[0m     )
[1;32m--> 311[0m [38;5;28;01mreturn[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py:457[0m, in [0;36mread_excel[1;34m(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, thousands, decimal, comment, skipfooter, convert_float, mangle_dupe_cols, storage_options)[0m
[0;32m    455[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[0;32m    456[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m--> 457[0m     io [38;5;241m=[39m [43mExcelFile[49m[43m([49m[43mio[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m[43m [49m[43mengine[49m[38;5;241;43m=[39;49m[43mengine[49m[43m)[49m
[0;32m    458[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[0;32m    459[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    460[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[0;32m    461[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[0;32m    462[0m     )

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py:1419[0m, in [0;36mExcelFile.__init__[1;34m(self, path_or_buffer, engine, storage_options)[0m
[0;32m   1416[0m [38;5;28mself[39m[38;5;241m.[39mengine [38;5;241m=[39m engine
[0;32m   1417[0m [38;5;28mself[39m[38;5;241m.[39mstorage_options [38;5;241m=[39m storage_options
[1;32m-> 1419[0m [38;5;28mself[39m[38;5;241m.[39m_reader [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engines[49m[43m[[49m[43mengine[49m[43m][49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_io[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_openpyxl.py:524[0m, in [0;36mOpenpyxlReader.__init__[1;34m(self, filepath_or_buffer, storage_options)[0m
[0;32m    509[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m(
[0;32m    510[0m     [38;5;28mself[39m,
[0;32m    511[0m     filepath_or_buffer: FilePath [38;5;241m|[39m ReadBuffer[[38;5;28mbytes[39m],
[0;32m    512[0m     storage_options: StorageOptions [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[0;32m    513[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[0;32m    514[0m     [38;5;124;03m"""[39;00m
[0;32m    515[0m [38;5;124;03m    Reader using openpyxl engine.[39;00m
[0;32m    516[0m 
[1;32m   (...)[0m
[0;32m    522[0m [38;5;124;03m        passed to fsspec for appropriate URLs (see ``_get_filepath_or_buffer``)[39;00m
[0;32m    523[0m [38;5;124;03m    """[39;00m
[1;32m--> 524[0m     [43mimport_optional_dependency[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mopenpyxl[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m    525[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(filepath_or_buffer, storage_options[38;5;241m=[39mstorage_options)

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\compat\_optional.py:141[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    139[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[0;32m    140[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[1;32m--> 141[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[0;32m    142[0m     [38;5;28;01melse[39;00m:
[0;32m    143[0m         [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

[1;31mImportError[0m: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

